# Generated by Django 5.2.6 on 2025-09-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250910_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(default='Other', max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
            ],
            options={
                'ordering': ['-last_used', '-updated_at', 'name'],
            },
        ),
    ]
