# Generated by Django 5.2.6 on 2025-09-10 00:23

from django.db import migrations
import os
import json
from django.conf import settings


def import_vendors_from_json(apps, schema_editor):
    Vendor = apps.get_model('core', 'Vendor')
    json_file_path = os.path.join(settings.BASE_DIR, 'vendors.json')
    
    if not os.path.exists(json_file_path):
        print(f"Warning: {json_file_path} not found. Skipping vendor import.")
        return
    
    try:
        with open(json_file_path, 'r') as f:
            data = json.load(f)
        
        imported_count = 0
        for vendor_data in data.get('vendors', []):
            # Skip vendors without names
            if not vendor_data.get('name'):
                continue
                
            # Create or update vendor
            vendor, created = Vendor.objects.get_or_create(
                name=vendor_data['name'],
                defaults={
                    'category': vendor_data.get('category', 'Other'),
                    'aliases': vendor_data.get('aliases', []),
                    'usage_count': vendor_data.get('usage_count', 0),
                    'source': vendor_data.get('source', 'manual'),
                }
            )
            
            if created:
                imported_count += 1
            else:
                # Update existing vendor
                vendor.category = vendor_data.get('category', vendor.category)
                vendor.aliases = vendor_data.get('aliases', vendor.aliases)
                vendor.usage_count = vendor_data.get('usage_count', vendor.usage_count)
                vendor.source = vendor_data.get('source', vendor.source)
                vendor.save()
        
        print(f"Successfully imported {imported_count} vendors from JSON file.")
        
    except Exception as e:
        print(f"Error importing vendors: {e}")


def reverse_import_vendors(apps, schema_editor):
    # This is a no-op for reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vendor'),
    ]

    operations = [
        migrations.RunPython(import_vendors_from_json, reverse_import_vendors),
    ]
