# Generated by Django 5.2.6 on 2025-09-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250910_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='total',
            field=models.CharField(blank=True, default='$0.00', max_length=20),
        ),
        migrations.AddField(
            model_name='file',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
