# Generated by Django 5.2.6 on 2025-09-10 00:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_file_date_file_invoice_number_file_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('CHARGE', 'Charge'), ('CREDIT', 'Credit'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], default='CHARGE', max_length=20)),
                ('card_holder', models.CharField(max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('PENDING', 'Pending')], default='UNMATCHED', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
