# Generated by Django 5.2.6 on 2025-09-10 00:53

from django.db import migrations
from decimal import Decimal
from datetime import date


def create_sample_transactions(apps, schema_editor):
    Transaction = apps.get_model('core', 'Transaction')
    
    sample_transactions = [
        {
            'date': date(2025, 8, 1),
            'amount': Decimal('60.00'),
            'description': '7-ELEVEN 46177 - 5682',
            'transaction_type': 'CHARGE',
            'card_holder': 'Edy Moncada',
            'due_date': date(2025, 8, 4),
            'status': 'UNMATCHED',
            'tags': []
        },
        {
            'date': date(2025, 8, 20),
            'amount': Decimal('2556.11'),
            'description': 'ACE BUILDING MATERIALS - 0684',
            'transaction_type': 'CHARGE',
            'card_holder': 'Alexis Linares',
            'due_date': date(2025, 8, 25),
            'status': 'UNMATCHED',
            'tags': []
        },
        {
            'date': date(2025, 6, 4),
            'amount': Decimal('-16.59'),
            'description': 'PURCHASE ADJUSTMENT - 1347',
            'transaction_type': 'CREDIT',
            'card_holder': 'Sharon Joch',
            'due_date': date(2025, 6, 9),
            'status': 'UNMATCHED',
            'tags': []
        },
        {
            'date': date(2025, 7, 15),
            'amount': Decimal('125.50'),
            'description': 'HOME DEPOT - 2847',
            'transaction_type': 'CHARGE',
            'card_holder': 'John Smith',
            'due_date': date(2025, 7, 20),
            'status': 'MATCHED',
            'tags': ['materials', 'construction']
        },
        {
            'date': date(2025, 7, 22),
            'amount': Decimal('89.99'),
            'description': 'LOWES - 1923',
            'transaction_type': 'CHARGE',
            'card_holder': 'Jane Doe',
            'due_date': date(2025, 7, 27),
            'status': 'PENDING',
            'tags': ['tools']
        },
        {
            'date': date(2025, 8, 5),
            'amount': Decimal('45.00'),
            'description': 'GAS STATION - 4456',
            'transaction_type': 'CHARGE',
            'card_holder': 'Mike Johnson',
            'due_date': date(2025, 8, 10),
            'status': 'UNMATCHED',
            'tags': ['fuel']
        },
        {
            'date': date(2025, 8, 12),
            'amount': Decimal('250.00'),
            'description': 'PAYMENT RECEIVED - 7891',
            'transaction_type': 'PAYMENT',
            'card_holder': 'Client ABC',
            'due_date': None,
            'status': 'MATCHED',
            'tags': ['payment', 'client']
        },
        {
            'date': date(2025, 8, 18),
            'amount': Decimal('75.25'),
            'description': 'OFFICE SUPPLIES - 3344',
            'transaction_type': 'CHARGE',
            'card_holder': 'Sarah Wilson',
            'due_date': date(2025, 8, 23),
            'status': 'UNMATCHED',
            'tags': ['office']
        }
    ]
    
    for transaction_data in sample_transactions:
        Transaction.objects.create(**transaction_data)


def reverse_sample_transactions(apps, schema_editor):
    Transaction = apps.get_model('core', 'Transaction')
    Transaction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction'),
    ]

    operations = [
        migrations.RunPython(create_sample_transactions, reverse_sample_transactions),
    ]
