# Generated by Django 5.2.6 on 2025-09-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_project_superintendent_and_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this class')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI display (e.g., #3B82F6)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='selected_class',
            field=models.ForeignKey(blank=True, help_text='Class selected during approval process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_files', to='core.class'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Classes this vendor belongs to', related_name='vendors', to='core.class'),
        ),
    ]
