# Generated by Django 5.2.6 on 2025-09-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_class_file_selected_class_vendor_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['parent__name', 'name'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent class for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.class'),
        ),
    ]
